/**
 * Default config for Alibaba-B2B-ICBU-F2E develop environment.
 * Auto-generated by Tianma v0.5.0
 */

var tianma = require('tianma'),
	pipe = tianma.pipe;

tianma
	.createHost({ port: 80 })
		.mount('/', [
			pipe.cache([
				pipe.combo({ source: 'loop://file.local/' }),
				pipe.proxy({
					'loop://file.local/$1': /\/\/.*?\/(.*)/
				})
			])
		])
		.mount('file.local', [
			pipe.static({ root: './htdocs' }),
			pipe.static({ root: '../build' }),
		])
		.start();